# Author
# Jorluis Perales
# Project URL on GitHub: https://github.com/jorluisperales/devops-playground-docker-compose

services:
  # GITLAB
  gitlab:
    image: gitlab/gitlab-ce:latest
    container_name: gitlab
    volumes:
      - gitlab-config:/etc/gitlab
      - gitlab-data:/var/opt/gitlab
      - gitlab-log:/var/log/gitlab
    ports:
      - 4000:80
    networks:
      - devops
      
  # JENKINS
  jenkins:
    image: jenkins/jenkins:latest
    container_name: jenkins
    volumes:
      - jenkins-data:/var/jenkins_home
    ports:
      - 4001:8080
      - 50000:50000
    networks:
      - devops
      
  # NEXUS
  nexus:
    image: sonatype/nexus:latest
    container_name: nexus
    volumes:
      - nexus-data:/opt/sonatype/nexus
    ports:
      - 4002:8081
    networks:
      - devops

  # SONARQUBE
  sonarqube:
    image: sonarqube:community
    hostname: sonarqube
    container_name: sonarqube
    depends_on:
      - db
    environment:
      SONAR_JDBC_URL: jdbc:postgresql://db:5432/sonar
      SONAR_JDBC_USERNAME: sonar
      SONAR_JDBC_PASSWORD: sonar
    volumes:
      - sonarqube_data:/opt/sonarqube/data
      - sonarqube_extensions:/opt/sonarqube/extensions
      - sonarqube_logs:/opt/sonarqube/logs
    ports:
      - "4003:9000"
    networks:
      - devops
  db:
    image: postgres:latest
    hostname: postgresql
    container_name: postgresql
    environment:
      POSTGRES_USER: sonar
      POSTGRES_PASSWORD: sonar
      POSTGRES_DB: sonar
    volumes:
      - postgresql:/var/lib/postgresql
      - postgresql_data:/var/lib/postgresql/data
    networks:
      - devops

  # RUNNER
  gitlab-runner:
    image: gitlab/gitlab-runner:alpine
    restart: always
    container_name: gitlab-runner1
    depends_on:
      - gitlab
    volumes:
      - gitlab-runner-config:/etc/gitlab-runner
      - /var/run/docker.sock:/var/run/docker.sock
    networks:
      - devops

networks:
  devops:
    external: true

volumes:
  gitlab-config:
  gitlab-data:
  gitlab-log:
  jenkins-data:
  nexus-data:
  sonarqube_data:
  sonarqube_extensions:
  sonarqube_logs:
  postgresql:
  postgresql_data:
  gitlab-runner-config:
